import{S as m,i as l}from"./assets/vendor-9310f15c.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const p=document.querySelector(".form");document.querySelector("input");document.querySelector(".gallery-box");const i=document.querySelector(".loader"),u=document.querySelector(".gallery"),c={key:"34228101-50b55348103eeb6dd10b59f8d",q:"cat",image_type:"photo",orientation:"horizontal",safesearch:!0},d=new m(".gallery a",{captionsData:"alt",captionDelay:250,nav:!0,close:!0,enableKeyboard:!0,docClose:!0});function g(o){return i.style.display="block",fetch(`https://pixabay.com/api/?${o}`).then(t=>{if(!t.ok)throw new Error(t.statusText);return t.json()}).then(({hits:t})=>{if(t.length>0){const s=t.reduce((a,e)=>a+`<li class="gallery-item">
                        <a href=${e.largeImageURL}>
                        <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}">
                        </a>
                        <div class="gallery-text-box">
                        <p>Likes: <span class="text-value">${e.likes}</span></p>
                        <p>Views: <span class="text-value">${e.views}</span></p>
                        <p>Comments: <span class="text-value">${e.comments}</span></p>
                        <p>Downloads: <span class="text-value">${e.downloads}</span></p>
                        </div>
                        </li>`,"");u.innerHTML=s,d.refresh()}else l.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}).catch(t=>{l.error({position:"topRight",message:`Error: ${t.message}. Please try again!`})}).finally(()=>{i.style.display="none"})}p.addEventListener("submit",o=>{o.preventDefault(),u.innerHTML="",c.q=o.target.elements.search.value.trim();const t=new URLSearchParams(c);g(t.toString()),o.currentTarget.reset()});
//# sourceMappingURL=commonHelpers.js.map
